"""Initial schema

Revision ID: 52a26c878bc0
Revises: 
Create Date: 2026-05-15 16:45:13.692548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a26c878bc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS gold_features_demo CASCADE')
    op.execute('DROP TABLE IF EXISTS silver_features_demo CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silver_features_demo',
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.BIGINT(), nullable=True),
    sa.Column('fvg_bullish', sa.BIGINT(), nullable=True),
    sa.Column('fvg_bearish', sa.BIGINT(), nullable=True),
    sa.Column('fvg_size', sa.FLOAT(), nullable=True),
    sa.Column('fvg_bullish_count', sa.FLOAT(), nullable=True),
    sa.Column('fvg_bearish_count', sa.FLOAT(), nullable=True),
    sa.Column('bos_bullish', sa.BIGINT(), nullable=True),
    sa.Column('bos_bearish', sa.BIGINT(), nullable=True),
    sa.Column('distance_from_swing_high', sa.FLOAT(), nullable=True),
    sa.Column('distance_from_swing_low', sa.FLOAT(), nullable=True),
    sa.Column('bos_bullish_count', sa.FLOAT(), nullable=True),
    sa.Column('bos_bearish_count', sa.FLOAT(), nullable=True),
    sa.Column('liquidity_sweep_high', sa.BIGINT(), nullable=True),
    sa.Column('liquidity_sweep_low', sa.BIGINT(), nullable=True),
    sa.Column('sweep_strength', sa.FLOAT(), nullable=True),
    sa.Column('liquidity_sweep_count', sa.FLOAT(), nullable=True),
    sa.Column('order_block_bullish', sa.BIGINT(), nullable=True),
    sa.Column('order_block_bearish', sa.BIGINT(), nullable=True),
    sa.Column('order_block_strength', sa.FLOAT(), nullable=True),
    sa.Column('order_block_count', sa.FLOAT(), nullable=True),
    sa.Column('premium_discount_position', sa.FLOAT(), nullable=True),
    sa.Column('in_premium', sa.BIGINT(), nullable=True),
    sa.Column('in_discount', sa.BIGINT(), nullable=True),
    sa.Column('distance_from_equilibrium', sa.FLOAT(), nullable=True),
    sa.Column('higher_high', sa.BIGINT(), nullable=True),
    sa.Column('higher_low', sa.BIGINT(), nullable=True),
    sa.Column('lower_high', sa.BIGINT(), nullable=True),
    sa.Column('lower_low', sa.BIGINT(), nullable=True),
    sa.Column('bullish_structure', sa.FLOAT(), nullable=True),
    sa.Column('bearish_structure', sa.FLOAT(), nullable=True),
    sa.Column('VWAPd_4', sa.FLOAT(), nullable=True),
    sa.Column('VWAPd_16', sa.FLOAT(), nullable=True),
    sa.Column('VWAPd_96', sa.FLOAT(), nullable=True),
    sa.Column('CVD_4', sa.FLOAT(), nullable=True),
    sa.Column('CVD_16', sa.FLOAT(), nullable=True),
    sa.Column('CVD_96', sa.FLOAT(), nullable=True),
    sa.Column('Imbal_4', sa.FLOAT(), nullable=True),
    sa.Column('Imbal_16', sa.FLOAT(), nullable=True),
    sa.Column('Imbal_96', sa.FLOAT(), nullable=True),
    sa.Column('Wick_4', sa.FLOAT(), nullable=True),
    sa.Column('Wick_16', sa.FLOAT(), nullable=True),
    sa.Column('Wick_96', sa.FLOAT(), nullable=True),
    sa.Column('Ret_4', sa.FLOAT(), nullable=True),
    sa.Column('Std_4', sa.FLOAT(), nullable=True),
    sa.Column('Ret_16', sa.FLOAT(), nullable=True),
    sa.Column('Std_16', sa.FLOAT(), nullable=True),
    sa.Column('Ret_96', sa.FLOAT(), nullable=True),
    sa.Column('Std_96', sa.FLOAT(), nullable=True),
    sa.Column('session_asia', sa.BIGINT(), nullable=True),
    sa.Column('session_london', sa.BIGINT(), nullable=True),
    sa.Column('session_ny', sa.BIGINT(), nullable=True),
    sa.Column('session_overlap', sa.BIGINT(), nullable=True),
    sa.Column('label', sa.FLOAT(), nullable=True)
    )
    op.create_table('gold_features_demo',
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.BIGINT(), nullable=True),
    sa.Column('fvg_bullish', sa.BIGINT(), nullable=True),
    sa.Column('fvg_bearish', sa.BIGINT(), nullable=True),
    sa.Column('fvg_size', sa.FLOAT(), nullable=True),
    sa.Column('fvg_bullish_count', sa.FLOAT(), nullable=True),
    sa.Column('fvg_bearish_count', sa.FLOAT(), nullable=True),
    sa.Column('bos_bullish', sa.BIGINT(), nullable=True),
    sa.Column('bos_bearish', sa.BIGINT(), nullable=True),
    sa.Column('distance_from_swing_high', sa.FLOAT(), nullable=True),
    sa.Column('distance_from_swing_low', sa.FLOAT(), nullable=True),
    sa.Column('bos_bullish_count', sa.FLOAT(), nullable=True),
    sa.Column('bos_bearish_count', sa.FLOAT(), nullable=True),
    sa.Column('liquidity_sweep_high', sa.BIGINT(), nullable=True),
    sa.Column('liquidity_sweep_low', sa.BIGINT(), nullable=True),
    sa.Column('sweep_strength', sa.FLOAT(), nullable=True),
    sa.Column('liquidity_sweep_count', sa.FLOAT(), nullable=True),
    sa.Column('order_block_bullish', sa.BIGINT(), nullable=True),
    sa.Column('order_block_bearish', sa.BIGINT(), nullable=True),
    sa.Column('order_block_strength', sa.FLOAT(), nullable=True),
    sa.Column('order_block_count', sa.FLOAT(), nullable=True),
    sa.Column('premium_discount_position', sa.FLOAT(), nullable=True),
    sa.Column('in_premium', sa.BIGINT(), nullable=True),
    sa.Column('in_discount', sa.BIGINT(), nullable=True),
    sa.Column('distance_from_equilibrium', sa.FLOAT(), nullable=True),
    sa.Column('higher_high', sa.BIGINT(), nullable=True),
    sa.Column('higher_low', sa.BIGINT(), nullable=True),
    sa.Column('lower_high', sa.BIGINT(), nullable=True),
    sa.Column('lower_low', sa.BIGINT(), nullable=True),
    sa.Column('bullish_structure', sa.FLOAT(), nullable=True),
    sa.Column('bearish_structure', sa.FLOAT(), nullable=True),
    sa.Column('VWAPd_4', sa.FLOAT(), nullable=True),
    sa.Column('VWAPd_16', sa.FLOAT(), nullable=True),
    sa.Column('VWAPd_96', sa.FLOAT(), nullable=True),
    sa.Column('CVD_4', sa.FLOAT(), nullable=True),
    sa.Column('CVD_16', sa.FLOAT(), nullable=True),
    sa.Column('CVD_96', sa.FLOAT(), nullable=True),
    sa.Column('Imbal_4', sa.FLOAT(), nullable=True),
    sa.Column('Imbal_16', sa.FLOAT(), nullable=True),
    sa.Column('Imbal_96', sa.FLOAT(), nullable=True),
    sa.Column('Wick_4', sa.FLOAT(), nullable=True),
    sa.Column('Wick_16', sa.FLOAT(), nullable=True),
    sa.Column('Wick_96', sa.FLOAT(), nullable=True),
    sa.Column('Ret_4', sa.FLOAT(), nullable=True),
    sa.Column('Std_4', sa.FLOAT(), nullable=True),
    sa.Column('Ret_16', sa.FLOAT(), nullable=True),
    sa.Column('Std_16', sa.FLOAT(), nullable=True),
    sa.Column('Ret_96', sa.FLOAT(), nullable=True),
    sa.Column('Std_96', sa.FLOAT(), nullable=True),
    sa.Column('session_asia', sa.BIGINT(), nullable=True),
    sa.Column('session_london', sa.BIGINT(), nullable=True),
    sa.Column('session_ny', sa.BIGINT(), nullable=True),
    sa.Column('session_overlap', sa.BIGINT(), nullable=True),
    sa.Column('label', sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
