import Link from 'next/link';
import { ArrowRight, Zap } from 'lucide-react';

export default function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center justify-center pt-14 overflow-hidden">
      <div className="absolute inset-0 opacity-[0.03]" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px)', backgroundSize: '60px 60px' }} />
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-emerald-500/5 blur-[150px] rounded-full pointer-events-none" />
      <div className="relative z-10 max-w-4xl mx-auto px-6 text-center space-y-10">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-border/50 bg-slate-800/30">
          <Zap className="w-3.5 h-3.5 text-emerald-400" aria-hidden="true" />
          <span className="text-[11px] font-medium uppercase tracking-widest text-slate-300">AI-powered smart money concepts</span>
        </div>
        <div className="space-y-5">
          <h1 className="text-5xl md:text-7xl font-black tracking-tight leading-[0.95]">
            Trade with<br />
            <span className="bg-gradient-to-r from-emerald-400 via-emerald-300 to-cyan-400 bg-clip-text text-transparent">machine precision</span>
          </h1>
          <p className="text-lg text-slate-300 max-w-xl mx-auto leading-relaxed">
            XAU/USD and XAG/USD signals generated by XGBoost models trained on
            real MT5 spot data. SHAP explainability on every prediction.
          </p>
        </div>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Link href="/auth/login" className="group px-8 py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl transition-all shadow-lg shadow-emerald-600/20 flex items-center justify-center gap-2">
            Start trading <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </Link>
          <Link href="/auth/login" className="px-8 py-4 bg-transparent hover:bg-accent/50 border border-border text-muted-foreground font-bold rounded-xl transition-all flex items-center justify-center">
            Sign in
          </Link>
        </div>
      </div>
    </section>
  );
}
