import Link from 'next/link';
import { ArrowRight, Zap } from 'lucide-react';

export default function Home() {
  return (
    <div className="relative min-h-screen flex flex-col items-center justify-center bg-background text-foreground p-6 overflow-hidden">
      {/* Grid pattern â€” trading terminal feel */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage:
            'linear-gradient(rgba(255,255,255,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.1) 1px, transparent 1px)',
          backgroundSize: '60px 60px',
        }}
      />

      {/* Subtle glow */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-emerald-500/5 blur-[150px] rounded-full pointer-events-none" />

      <div className="relative z-10 flex flex-col items-center text-center space-y-10 max-w-4xl">
        {/* Eyebrow */}
        <div className="flex items-center gap-2 px-4 py-1.5 rounded-full border border-border/50 bg-slate-800/30">
          <Zap className="w-3.5 h-3.5 text-emerald-400" />
          <span className="text-[11px] font-medium uppercase tracking-widest text-slate-400">
            AI-powered smart money concepts
          </span>
        </div>

        {/* Headline */}
        <div className="space-y-5">
          <h1 className="text-5xl md:text-7xl font-black tracking-tight leading-[0.95]">
            Trade with
            <br />
            <span className="bg-gradient-to-r from-emerald-400 via-emerald-300 to-cyan-400 bg-clip-text text-transparent">
              machine precision
            </span>
          </h1>
          <p className="text-lg text-slate-400 max-w-xl mx-auto leading-relaxed">
            XAU/USD and XAG/USD signals generated by XGBoost models trained on
            20 years of tick data. SHAP explainability on every prediction.
          </p>
        </div>

        {/* CTA */}
        <div className="flex flex-col sm:flex-row gap-4">
          <Link
            href="/auth/login"
            className="group px-8 py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl transition-all shadow-lg shadow-emerald-600/20 flex items-center justify-center gap-2"
          >
            Open dashboard
            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </Link>
          <Link
            href="https://github.com/Talha/ml-signals"
            className="px-8 py-4 bg-transparent hover:bg-accent/50 border border-border text-muted-foreground font-bold rounded-xl transition-all flex items-center justify-center"
          >
            View source
          </Link>
        </div>

        {/* Live ticker strip */}
        <div className="w-full max-w-2xl pt-8 border-t border-border/50">
          <div className="grid grid-cols-3 gap-8 text-center">
            <div>
              <span className="text-3xl md:text-4xl font-black font-mono text-card-foreground">
                XAU
              </span>
              <p className="text-[10px] uppercase tracking-widest text-emerald-500 mt-1">
                Gold
              </p>
            </div>
            <div>
              <span className="text-3xl md:text-4xl font-black font-mono text-card-foreground">
                XAG
              </span>
              <p className="text-[10px] uppercase tracking-widest text-slate-500 mt-1">
                Silver
              </p>
            </div>
            <div>
              <span className="text-3xl md:text-4xl font-black font-mono text-emerald-400">
                89
              </span>
              <p className="text-[10px] uppercase tracking-widest text-slate-500 mt-1">
                Features
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
