import Link from 'next/link';
import { ArrowRight, Zap } from 'lucide-react';
import LiveTicker from '@/components/Landing/LiveTicker';

export default function Home() {
  return (
    <div className="relative min-h-screen flex flex-col items-center justify-center bg-background text-foreground p-6 overflow-hidden">
      {/* ── Dot grid overlay ── */}
      <div
        className="absolute inset-0 opacity-[0.06]"
        style={{
          backgroundImage:
            'radial-gradient(circle, rgba(255,255,255,0.5) 1px, transparent 1px)',
          backgroundSize: '24px 24px',
        }}
      />

      {/* ── Asymmetric radial mesh glows ── */}
      <div className="absolute top-1/4 left-1/3 -translate-x-1/2 w-[700px] h-[400px] bg-emerald-600/8 blur-[180px] rounded-full pointer-events-none" />
      <div className="absolute top-1/3 right-1/4 translate-x-1/4 w-[500px] h-[350px] bg-cyan-500/6 blur-[160px] rounded-full pointer-events-none" />
      <div className="absolute bottom-1/4 left-1/2 -translate-x-1/2 w-[400px] h-[250px] bg-emerald-400/4 blur-[140px] rounded-full pointer-events-none" />

      <div className="relative z-10 flex flex-col items-center text-center space-y-10 max-w-4xl">
        {/* ── Eyebrow chip ── */}
        <div className="flex items-center gap-2 px-4 py-1.5 rounded-full border border-white/10 bg-white/[0.03] backdrop-blur-sm">
          <Zap className="w-3.5 h-3.5 text-emerald-400" />
          <span className="text-[11px] font-medium uppercase tracking-widest text-slate-400">
            AI-powered smart money concepts
          </span>
        </div>

        {/* ── Live price ticker (item 1) ── */}
        <LiveTicker />

        {/* ── Headline with glow (item 3) ── */}
        <div className="space-y-6">
          <h1 className="text-5xl md:text-7xl lg:text-8xl font-black tracking-[-0.03em] leading-[0.92]">
            Trade with
            <br />
            <span className="relative">
              <span
                className="absolute inset-0 bg-gradient-to-r from-emerald-500 via-emerald-300 to-cyan-400 blur-2xl opacity-30 pointer-events-none"
                aria-hidden
              />
              <span className="relative bg-gradient-to-r from-emerald-500 via-emerald-300 to-cyan-400 bg-clip-text text-transparent">
                machine precision
              </span>
            </span>
          </h1>
          <p className="text-lg md:text-xl text-slate-400 max-w-xl mx-auto leading-relaxed tracking-wide">
            XAU/USD and XAG/USD signals generated by XGBoost models trained on
            20 years of tick data. SHAP explainability on every prediction.
          </p>
        </div>

        {/* ── CTA: primary + text link (item 5) ── */}
        <div className="flex flex-col sm:flex-row items-center gap-6">
          <Link
            href="/auth/login"
            className="group px-8 py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl transition-all shadow-lg shadow-emerald-600/20 flex items-center justify-center gap-2"
          >
            Open dashboard
            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </Link>
          <Link
            href="https://github.com/Talha4565/MetalMind-SMCForge"
            className="text-sm font-medium text-slate-500 hover:text-slate-300 transition-colors"
          >
            View source on GitHub
          </Link>
        </div>

        {/* ── Dashboard screenshot peek (item 2) ── */}
        <div className="relative w-full max-w-3xl mt-4">
          <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-background via-background/80 to-transparent z-10 pointer-events-none" />
          <div className="rounded-xl border border-white/10 bg-white/[0.02] overflow-hidden shadow-2xl shadow-black/40">
            <div className="flex items-center gap-1.5 px-3 py-2 border-b border-white/5 bg-white/[0.02]">
              <span className="w-2 h-2 rounded-full bg-zinc-700" />
              <span className="w-2 h-2 rounded-full bg-zinc-700" />
              <span className="w-2 h-2 rounded-full bg-zinc-700" />
              <span className="ml-2 text-[9px] font-mono text-zinc-600 tracking-wider">METALMIND SMCFORGE</span>
            </div>
            <div className="relative h-[280px] md:h-[360px] bg-[#0a0b0d] flex items-center justify-center overflow-hidden">
              {/* Terminal-style placeholder that looks like the real dashboard */}
              <div className="absolute inset-0 p-4 grid grid-cols-[200px_1fr_180px] gap-px opacity-60">
                {/* Left panel mock */}
                <div className="border border-white/5 rounded bg-white/[0.02] p-3 space-y-2">
                  <div className="h-2 w-16 bg-emerald-500/30 rounded" />
                  <div className="h-6 w-full bg-emerald-500/10 rounded border border-emerald-500/20 flex items-center px-2">
                    <span className="text-[8px] font-mono text-emerald-400">BUY</span>
                  </div>
                  <div className="space-y-1.5 mt-3">
                    {[0.4, 0.3, 0.25, 0.2, 0.15].map((w, i) => (
                      <div key={i} className="flex items-center gap-1.5">
                        <div className="h-1 flex-1 bg-white/5 rounded overflow-hidden">
                          <div className="h-full bg-emerald-500/40 rounded" style={{ width: `${w * 100}%` }} />
                        </div>
                        <span className="text-[6px] font-mono text-zinc-600 w-6 text-right">{(w * 0.8).toFixed(2)}</span>
                      </div>
                    ))}
                  </div>
                </div>
                {/* Center chart mock */}
                <div className="border border-white/5 rounded bg-white/[0.02] relative overflow-hidden">
                  <svg className="absolute inset-0 w-full h-full" viewBox="0 0 600 300" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="rgb(16,185,129)" stopOpacity="0.15" />
                        <stop offset="100%" stopColor="rgb(16,185,129)" stopOpacity="0" />
                      </linearGradient>
                    </defs>
                    <path
                      d="M0,200 C50,180 100,160 150,170 C200,180 250,120 300,100 C350,80 400,110 450,90 C500,70 550,60 600,50 L600,300 L0,300 Z"
                      fill="url(#chartGrad)"
                    />
                    <path
                      d="M0,200 C50,180 100,160 150,170 C200,180 250,120 300,100 C350,80 400,110 450,90 C500,70 550,60 600,50"
                      fill="none"
                      stroke="rgb(16,185,129)"
                      strokeWidth="1.5"
                      opacity="0.6"
                    />
                  </svg>
                  {/* Candlestick silhouettes */}
                  <div className="absolute bottom-4 left-4 right-4 flex items-end gap-px opacity-30">
                    {Array.from({ length: 40 }, (_, i) => {
                      const h = 20 + Math.sin(i * 0.4) * 30 + Math.random() * 20;
                      const green = Math.random() > 0.4;
                      return (
                        <div key={i} className="flex-1 flex flex-col items-center gap-px">
                          <div className="w-px bg-white/20" style={{ height: `${h * 0.3}px` }} />
                          <div
                            className="w-full max-w-[4px] rounded-sm"
                            style={{
                              height: `${h}px`,
                              backgroundColor: green ? 'rgba(16,185,129,0.4)' : 'rgba(239,68,68,0.3)',
                            }}
                          />
                          <div className="w-px bg-white/20" style={{ height: `${h * 0.2}px` }} />
                        </div>
                      );
                    })}
                  </div>
                </div>
                {/* Right panel mock */}
                <div className="border border-white/5 rounded bg-white/[0.02] p-3 space-y-2">
                  <div className="h-2 w-12 bg-zinc-600 rounded" />
                  <div className="grid grid-cols-2 gap-1.5">
                    {['3268', '0.81', 'BUY', '+0.34%'].map((v, i) => (
                      <div key={i} className="h-8 bg-white/[0.03] rounded border border-white/5 flex items-center justify-center">
                        <span className="text-[7px] font-mono text-zinc-500">{v}</span>
                      </div>
                    ))}
                  </div>
                  <div className="space-y-1.5 mt-2">
                    {[0.6, 0.45, 0.3].map((w, i) => (
                      <div key={i} className="h-1.5 bg-white/5 rounded overflow-hidden">
                        <div className="h-full bg-cyan-500/30 rounded" style={{ width: `${w * 100}%` }} />
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ── Metric cards (item 4 — monospace) ── */}
        <div className="w-full max-w-2xl pt-4">
          <div className="grid grid-cols-3 gap-5">
            <div className="rounded-xl border border-zinc-800 bg-white/[0.03] backdrop-blur-sm px-6 py-6 text-center transition-colors hover:border-zinc-700 hover:bg-white/[0.05]">
              <span className="text-3xl md:text-4xl font-black font-mono text-card-foreground tabular-nums block">
                XAU
              </span>
              <p className="text-[10px] uppercase tracking-[0.2em] text-emerald-500 mt-2 font-medium">
                Gold
              </p>
            </div>
            <div className="rounded-xl border border-zinc-800 bg-white/[0.03] backdrop-blur-sm px-6 py-6 text-center transition-colors hover:border-zinc-700 hover:bg-white/[0.05]">
              <span className="text-3xl md:text-4xl font-black font-mono text-card-foreground tabular-nums block">
                XAG
              </span>
              <p className="text-[10px] uppercase tracking-[0.2em] text-slate-500 mt-2 font-medium">
                Silver
              </p>
            </div>
            <div className="rounded-xl border border-zinc-800 bg-white/[0.03] backdrop-blur-sm px-6 py-6 text-center transition-colors hover:border-zinc-700 hover:bg-white/[0.05]">
              <span className="text-3xl md:text-4xl font-black font-mono text-emerald-400 tabular-nums block">
                89
              </span>
              <p className="text-[10px] uppercase tracking-[0.2em] text-slate-500 mt-2 font-medium">
                Features
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
